apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: prometheus-operator
    meta.helm.sh/release-namespace: obs
  creationTimestamp: "2022-03-28T16:06:10Z"
  generation: 1
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus
    helm.sh/chart: kube-prometheus-6.8.2
  name: prometheus-operator-kube-p-operator
  namespace: obs
  resourceVersion: "1351"
  uid: 36060ff9-548d-4a34-9549-577be23a9a7a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/instance: prometheus-operator
      app.kubernetes.io/name: kube-prometheus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: operator
        app.kubernetes.io/instance: prometheus-operator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kube-prometheus
        helm.sh/chart: kube-prometheus-6.8.2
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: operator
                  app.kubernetes.io/instance: prometheus-operator
                  app.kubernetes.io/name: kube-prometheus
              namespaces:
              - obs
              topologyKey: kubernetes.io/hostname
            weight: 1
      podAntiAffinity:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/__elba__/metrics'
        prometheus.io/port: '8080'
      containers:
      - args:
        - --kubelet-service=kube-system/prometheus-operator-kube-p-kubelet
        - --log-format=logfmt
        - --log-level=info
        - --localhost=127.0.0.1
        - --prometheus-config-reloader=$(PROMETHEUS_CONFIG_RELOADER)
        env:
        - name: PROMETHEUS_CONFIG_RELOADER
          valueFrom:
            configMapKeyRef:
              key: prometheus-config-reloader
              name: prometheus-operator-kube-p-operator
        image: docker.io/bitnami/prometheus-operator:0.55.1-debian-10-r1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /metrics
            port: http
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /metrics
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      serviceAccount: prometheus-operator-kube-p-operator
      serviceAccountName: prometheus-operator-kube-p-operator
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2022-03-28T16:06:11Z"
    lastUpdateTime: "2022-03-28T16:06:11Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2022-03-28T16:06:11Z"
    lastUpdateTime: "2022-03-28T16:06:11Z"
    message: ReplicaSet "prometheus-operator-kube-p-operator-79f7784978" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
